const {db,ref,set,update,onValue,get,push,serverTimestamp}=window.FirebaseGame;
let room="",pid="",pname="",avatar="",data=null,timerInt=null;
const $=id=>document.getElementById(id), path=()=>`pookieCrorepatiRooms/${room}`, r=()=>ref(db,path());
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active")}
function roomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()} function playerId(){return "p_"+Date.now()+"_"+Math.floor(Math.random()*999)}
function qs(cat){return cat==="mixed"?Object.values(QUESTION_BANK).flat():(QUESTION_BANK[cat]||QUESTION_BANK.funny)}
function pick(cat,used=[]){let list=qs(cat);if(used.length>=list.length)used=[];let i;do{i=Math.floor(Math.random()*list.length)}while(used.includes(i));return i}
function nowQ(){return qs(data.settings.category)[data.qIndex]} function prize(l){return l<=0?"₹0":MONEY_LADDER[l-1]||MONEY_LADDER.at(-1)} function safe(l){return l>=10?MONEY_LADDER[9]:l>=5?MONEY_LADDER[4]:"₹0"}
function newP(n,a){return{name:n,avatar:a,level:0,money:"₹0",wrong:0,eliminated:false,lifelines:{fifty:false,audience:false,friend:false,ai:false,swap:false,skip:false},joinedAt:Date.now()}}
$("createBtn").onclick=async()=>{pname=$("createName").value.trim();avatar=$("createAvatar").value;if(!pname)return $("homeMsg").textContent="Enter name macha";room=roomCode();pid=playerId();let cat=$("category").value,max=+$("playerMode").value,qi=pick(cat,[]);await set(r(),{host:pid,status:"lobby",maxPlayers:max,settings:{category:cat,timer:30},turn:0,qIndex:qi,used:[qi],answered:false,selected:-1,showCorrect:false,winner:"",chat:{},players:{[pid]:newP(pname,avatar)},createdAt:serverTimestamp()});enter()}
$("joinBtn").onclick=async()=>{pname=$("joinName").value.trim();avatar=$("joinAvatar").value;room=$("joinCode").value.trim().toUpperCase();if(!pname||!room)return $("homeMsg").textContent="Enter name and code";let s=await get(r());if(!s.exists())return $("homeMsg").textContent="Room not found";let d=s.val();if(Object.keys(d.players||{}).length>=d.maxPlayers)return $("homeMsg").textContent="Room full";pid=playerId();await update(ref(db,`${path()}/players/${pid}`),newP(pname,avatar));enter()}
function enter(){$("roomCode").textContent=room;show("lobbyScreen");onValue(r(),s=>{data=s.val();if(!data)return;if(data.status==="lobby")renderLobby();if(data.status==="playing")renderGame();if(data.status==="final")renderFinal()})}
function renderLobby(){show("lobbyScreen");let ps=data.players||{};$("modeText").textContent=`Mode: ${data.maxPlayers} players • Category: ${data.settings.category}`;$("lobbyPlayers").innerHTML=Object.entries(ps).map(([id,p])=>`<div class="player ${id===pid?"active":""}"><div class="avatar">${p.avatar}</div><b>${p.name}</b><p>${id===data.host?"👑 Host":"Player"}</p></div>`).join("");$("startBtn").style.display=data.host===pid?"block":"none";$("lobbyMsg").textContent=Object.keys(ps).length===data.maxPlayers?"Ready pookie!":"Waiting for friends..."}
$("copyBtn").onclick=()=>navigator.clipboard.writeText(room);
$("startBtn").onclick=async()=>{if(data.host!==pid)return;if(Object.keys(data.players).length!==data.maxPlayers)return $("lobbyMsg").textContent=`Need ${data.maxPlayers} players`;await update(r(),{status:"playing",questionStart:Date.now(),answered:false,selected:-1,showCorrect:false})}
function renderGame(){show("gameScreen");let ids=Object.keys(data.players),cur=ids[data.turn%ids.length],p=data.players[cur],mine=cur===pid,q=nowQ();$("turnBadge").textContent=`${p.avatar} ${p.name}'s Turn`;$("qBadge").textContent=`Q${p.level+1}`;$("catBadge").textContent=data.settings.category;$("questionText").textContent=q.question;$("hostText").textContent=data.answered?"Answer locked!":mine?"Your turn macha, choose carefully!":`${p.name} is playing now`;renderOptions(q,mine);renderScore(ids,cur);renderLadder(p.level);renderLife(mine,p);renderChat();turnTimer(mine)}
function renderOptions(q,mine){$("options").innerHTML=q.options.map((op,i)=>{let c="opt";if(data.showCorrect&&i===q.answer)c+=" correct";if(data.showCorrect&&i===data.selected&&i!==q.answer)c+=" wrong";return`<button class="${c}" ${!mine||data.answered?"disabled":""} onclick="ans(${i})">${String.fromCharCode(65+i)}. ${op}</button>`}).join("")}
function renderScore(ids,cur){$("scoreBoard").innerHTML=ids.map(id=>{let p=data.players[id];return`<div class="scoreItem ${id===cur?"active":""}"><div class="avatar">${p.avatar}</div><b>${p.name}</b><div class="money">${p.money}</div><small>Level ${p.level}/14 • Wrong ${p.wrong}/2</small>${p.eliminated?"<p>❌ Out</p>":""}</div>`}).join("")}
function renderLadder(l){$("ladder").innerHTML=MONEY_LADDER.map((m,i)=>`<div class="step ${i===l?"now":""} ${i===4||i===9?"safe":""}"><span>Q${i+1}</span><b>${m}</b></div>`).reverse().join("")}
function renderLife(mine,p){["fifty","audience","friend","ai","swap","skip"].forEach(x=>$(x).disabled=!mine||data.answered||p.lifelines[x])}
function turnTimer(active){clearInterval(timerInt);let tick=()=>{let left=Math.max(0,data.settings.timer-Math.floor((Date.now()-data.questionStart)/1000));$("timer").textContent=left;if(active&&!data.answered&&left<=0){clearInterval(timerInt);ans(-1)}};tick();timerInt=setInterval(tick,500)}
window.ans=async(i)=>{let ids=Object.keys(data.players),cur=ids[data.turn%ids.length];if(cur!==pid||data.answered)return;let q=nowQ(),ok=i===q.answer;await update(r(),{answered:true,selected:i,showCorrect:true});let p=data.players[pid];if(ok)await update(ref(db,`${path()}/players/${pid}`),{level:p.level+1,money:prize(p.level+1)});else await update(ref(db,`${path()}/players/${pid}`),{wrong:p.wrong+1,eliminated:p.wrong+1>=2,money:p.wrong+1>=2?safe(p.level):p.money});setTimeout(nextTurn,1700)}
async function nextTurn(){let s=await get(r()),d=s.val(),ids=Object.keys(d.players),alive=ids.filter(id=>!d.players[id].eliminated&&d.players[id].level<14);if(alive.length<=1)return finish(d);let next=d.turn;do{next=(next+1)%ids.length}while(d.players[ids[next]].eliminated);let qi=pick(d.settings.category,d.used||[]);await update(r(),{turn:next,qIndex:qi,used:[...(d.used||[]),qi],answered:false,selected:-1,showCorrect:false,questionStart:Date.now()})}
async function finish(d){let arr=Object.values(d.players).sort((a,b)=>MONEY_LADDER.indexOf(b.money)-MONEY_LADDER.indexOf(a.money));await update(r(),{status:"final",winner:arr[0].name})}
async function mark(x){let p=data.players[pid];await update(ref(db,`${path()}/players/${pid}/lifelines`),{...p.lifelines,[x]:true});$("resultCard").classList.remove("hidden")}
$("fifty").onclick=async()=>{await mark("fifty");let q=nowQ(),wr=[0,1,2,3].filter(i=>i!==q.answer).sort(()=>Math.random()-.5).slice(0,2);$("resultTitle").textContent="50:50 ✂️";$("resultText").innerHTML=`Remove options: <b>${wr.map(i=>String.fromCharCode(65+i)).join(", ")}</b>`}
$("audience").onclick=async()=>{await mark("audience");let q=nowQ(),poll=[0,0,0,0],cp=Math.floor(Math.random()*25)+55,rest=100-cp;poll[q.answer]=cp;[0,1,2,3].filter(i=>i!==q.answer).forEach((i,k,a)=>{if(k===a.length-1)poll[i]=rest;else{let v=Math.floor(Math.random()*rest);poll[i]=v;rest-=v}});$("resultTitle").textContent="Audience Poll 👥";$("resultText").innerHTML=poll.map((p,i)=>`<div class="poll"><b>${String.fromCharCode(65+i)} ${p}%</b><div class="bar"><div class="fill" style="width:${p}%"></div></div></div>`).join("")}
$("friend").onclick=async()=>{await mark("friend");let q=nowQ();$("resultTitle").textContent="Call Pookie ☎️";$("resultText").innerHTML=`Pookie says: I think answer is <b>${String.fromCharCode(65+q.answer)}</b> 💖`}
$("ai").onclick=async()=>{await mark("ai");let q=nowQ(),sug=Math.random()<.8?q.answer:Math.floor(Math.random()*4);$("resultTitle").textContent="AI Pookie 🤖";$("resultText").innerHTML=`AI suggests <b>${String.fromCharCode(65+sug)}</b>`}
$("swap").onclick=async()=>{await mark("swap");let qi=pick(data.settings.category,data.used||[]);await update(r(),{qIndex:qi,used:[...(data.used||[]),qi],questionStart:Date.now(),answered:false,selected:-1,showCorrect:false})}
$("skip").onclick=async()=>{await mark("skip");nextTurn()}
$("sendChat").onclick=sendChat;$("chatInput").onkeydown=e=>{if(e.key==="Enter")sendChat()}
async function sendChat(){let t=$("chatInput").value.trim();if(!t)return;await push(ref(db,`${path()}/chat`),{name:pname,avatar,text:t,time:Date.now()});$("chatInput").value=""}
function renderChat(){let msgs=Object.values(data.chat||{}).slice(-20);$("chatBox").innerHTML=msgs.map(m=>`<div class="chatMsg">${m.avatar} <b>${m.name}</b>: ${esc(m.text)}</div>`).join("");$("chatBox").scrollTop=$("chatBox").scrollHeight}
function esc(t){return t.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderFinal(){show("finalScreen");let arr=Object.values(data.players).sort((a,b)=>MONEY_LADDER.indexOf(b.money)-MONEY_LADDER.indexOf(a.money));$("winnerBox").innerHTML=`<h2>${arr[0].avatar} ${arr[0].name} wins!</h2><div class="money">${arr[0].money}</div>${arr.map((p,i)=>`<p>${i+1}. ${p.avatar} ${p.name} — ${p.money}</p>`).join("")}`}
